//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by InetDownload.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INETDOWNLOAD_DIALOG         102
#define IDS_HTTPDOWNLOAD_FILESTATUS     102
#define IDS_HTTPDOWNLOAD_CONNECTED      103
#define IDS_HTTPDOWNLOAD_RESOLVING_NAME 104
#define IDS_HTTPDOWNLOAD_RESOLVED_NAME  105
#define IDS_HTTPDOWNLOAD_CONNECTING     106
#define IDS_HTTPDOWNLOAD_REDIRECTING    107
#define IDS_HTTPDOWNLOAD_GETTING_FILE_INFORMATION 108
#define IDS_HTTPDOWNLOAD_FAIL_PARSE_ERROR 109
#define IDS_HTTPDOWNLOAD_GENERIC_ERROR  110
#define IDS_HTTPDOWNLOAD_FAIL_CONNECT_SERVER 111
#define IDS_HTTPDOWNLOAD_INVALID_SERVER_RESPONSE 112
#define IDS_HTTPDOWNLOAD_INVALID_HTTP_RESPONSE 113
#define IDS_HTTPDOWNLOAD_ERROR_READFILE 114
#define IDS_HTTPDOWNLOAD_PERCENTAGE     115
#define IDS_HTTPDOWNLOAD_RETREIVEING_FILE 116
#define IDS_HTTPDOWNLOAD_OF             117
#define IDS_HTTPDOWNLOAD_SECONDS        118
#define IDS_HTTPDOWNLOAD_MINUTES        119
#define IDS_HTTPDOWNLOAD_MINUTES_AND_SECONDS 120
#define IDS_HTTPDOWNLOAD_BYTES          121
#define IDR_MAINFRAME                   122
#define IDS_HTTPDOWNLOAD_KILOBYTES      123
#define IDD_HTTPDOWNLOAD                124
#define IDS_HTTPDOWNLOAD_MEGABYTES      125
#define IDR_HTTPDOWNLOAD_ANIMATION      126
#define IDS_HTTPDOWNLOAD_TIMELEFT       127
#define IDS_HTTPDOWNLOAD_BYTESPERSECOND 128
#define IDS_HTTPDOWNLOAD_KILOBYTESPERSECOND 129
#define IDS_HTTPDOWNLOAD_OK_TO_OVERWRITE 130
#define IDS_HTTPDOWNLOAD_FAIL_FILE_OPEN 131
#define IDS_HTTPDOWNLOAD_ABORTING_TRANSFER 132
#define IDC_ANIMATE1                    1000
#define IDC_STATUS                      1001
#define IDC_FILESTATUS                  1002
#define IDC_PROGRESS1                   1003
#define IDC_TIMELEFT                    1004
#define IDC_TRANSFER_RATE               1005
#define IDC_BUTTON1                     1005
#define IDC_DOWNLOAD                    1005
#define IDC_URL                         1006
#define IDC_FILE                        1007
#define IDC_USER                        1008
#define IDC_PASSWORD                    1009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
